import type { DocumentRole, PrimaryDomain } from "../domain/taxonomy";

export type FileMappingRule = {
  id: string; primaryDomain: PrimaryDomain; documentRole: DocumentRole; requiredHeaders?: string[];
  anyHeaders?: string[]; sheetPatterns?: RegExp[]; titlePatterns?: RegExp[]; filenamePatterns?: RegExp[];
  textPatterns?: RegExp[]; entityCandidates?: string[]; primaryKeyCandidates?: string[];
  joinKeyCandidates?: string[]; confidence: number; explanation: string; trustFilenameOnly?: boolean;
};

export const fileMappingRules: FileMappingRule[] = [
  { id: "gdpdu-asset-master", primaryDomain: "fixed_assets", documentRole: "master_data", filenamePatterns: [/^AV\/Anlagen\.txt$/i], primaryKeyCandidates: ["anlagennummer"], joinKeyCandidates: ["anlagennummer"], confidence: 0.96, trustFilenameOnly: true, explanation: "Observed GDPdU fixed-asset master-data filename and folder." },
  { id: "gdpdu-asset-transactions", primaryDomain: "fixed_assets", documentRole: "transactions", filenamePatterns: [/^AV\/Anlagenbuchungen\.txt$/i], primaryKeyCandidates: ["anlagennummer"], joinKeyCandidates: ["anlagennummer", "sachkonto"], confidence: 0.95, trustFilenameOnly: true, explanation: "Observed GDPdU fixed-asset transaction filename and folder." },
  { id: "gdpdu-gl-account-master", primaryDomain: "general_ledger", documentRole: "master_data", filenamePatterns: [/^Sachkonten\/Sachkonten\.txt$/i], primaryKeyCandidates: ["sachkonto"], joinKeyCandidates: ["sachkonto"], confidence: 0.96, trustFilenameOnly: true, explanation: "Observed GDPdU general-ledger account-master filename and folder." },
  { id: "gdpdu-gl-transactions", primaryDomain: "general_ledger", documentRole: "transactions", filenamePatterns: [/^Sachkonten\/Sachkontobuchungen\.txt$/i], primaryKeyCandidates: ["belegnummer"], joinKeyCandidates: ["sachkonto", "belegnummer"], confidence: 0.96, trustFilenameOnly: true, explanation: "Observed GDPdU general-ledger transaction filename and folder." },
  { id: "gdpdu-vendor-master", primaryDomain: "accounts_payable", documentRole: "master_data", filenamePatterns: [/^Kreditoren\/Lieferanten\.txt$/i], primaryKeyCandidates: ["kreditorennummer"], joinKeyCandidates: ["kreditorennummer"], confidence: 0.96, trustFilenameOnly: true, explanation: "Observed GDPdU vendor master-data filename and folder." },
  { id: "gdpdu-vendor-transactions", primaryDomain: "accounts_payable", documentRole: "transactions", filenamePatterns: [/^Kreditoren\/Lieferantenbuchungen\.txt$/i], primaryKeyCandidates: ["belegnummer"], joinKeyCandidates: ["kreditorennummer", "belegnummer"], confidence: 0.96, trustFilenameOnly: true, explanation: "Observed GDPdU vendor transaction filename and folder." },
  { id: "gdpdu-customer-master", primaryDomain: "accounts_receivable", documentRole: "master_data", filenamePatterns: [/^Debitoren\/Kunden\.txt$/i], primaryKeyCandidates: ["debitorennummer"], joinKeyCandidates: ["debitorennummer"], confidence: 0.96, trustFilenameOnly: true, explanation: "Observed GDPdU customer master-data filename and folder." },
  { id: "gdpdu-customer-transactions", primaryDomain: "accounts_receivable", documentRole: "transactions", filenamePatterns: [/^Debitoren\/Kundenbuchungen\.txt$/i], primaryKeyCandidates: ["belegnummer"], joinKeyCandidates: ["debitorennummer", "belegnummer"], confidence: 0.96, trustFilenameOnly: true, explanation: "Observed GDPdU customer transaction filename and folder." },
  { id: "trial-balance", primaryDomain: "financial_reporting", documentRole: "reconciliation", filenamePatterns: [/Saldenliste/i], sheetPatterns: [/Saldenliste|Überleitung/i], titlePatterns: [/Summen- und Saldenliste|Saldenliste|Überleitung JA/i], primaryKeyCandidates: ["sachkonto"], joinKeyCandidates: ["sachkonto"], confidence: 0.94, explanation: "Observed trial-balance or financial-statement reconciliation marker." },
  { id: "subledger-reconciliation", primaryDomain: "financial_reporting", documentRole: "reconciliation", filenamePatterns: [/Abstimmung_Nebenbuecher_HB/i], sheetPatterns: [/Abstimmung/i], titlePatterns: [/Abstimmung Nebenbücher|Hauptbuch/i], joinKeyCandidates: ["sachkonto"], confidence: 0.94, explanation: "Observed subledger-to-general-ledger reconciliation marker." },
  { id: "permissions-report", primaryDomain: "controls_permissions", documentRole: "control_evidence", filenamePatterns: [/Berechtigungsauswertung/i], sheetPatterns: [/Berechtigungen/i], titlePatterns: [/Berechtigungsauswertung|D365/i], primaryKeyCandidates: ["user"], joinKeyCandidates: ["user", "rolle"], confidence: 0.95, explanation: "Observed D365 permissions extract." },
  { id: "journal-approval-log", primaryDomain: "controls_permissions", documentRole: "control_evidence", requiredHeaders: ["ERFASSUNGSNUMMER", "FREIGEBER", "FREIGABESTATUS"], filenamePatterns: [/Freigabe-Log/i], primaryKeyCandidates: ["ERFASSUNGSNUMMER"], joinKeyCandidates: ["JOURNALNAME", "FREIGEBER"], confidence: 0.95, explanation: "Observed journal approval-log control evidence." },
  { id: "master-data-change-log", primaryDomain: "controls_permissions", documentRole: "control_evidence", requiredHeaders: ["GEAENDERT_VON", "GENEHMIGT_VON", "GENEHMIGT"], filenamePatterns: [/Stammdatenaenderungen/i], primaryKeyCandidates: ["KONTO"], joinKeyCandidates: ["KONTO", "GEAENDERT_VON", "GENEHMIGT_VON"], confidence: 0.95, explanation: "Observed master-data change approval evidence." },
  { id: "it-completeness-confirmation", primaryDomain: "supporting_documents", documentRole: "control_evidence", filenamePatterns: [/IT-Bestaetigung/i], titlePatterns: [/Bestätigung der IT|Unveränderbarkeit/i], confidence: 0.97, trustFilenameOnly: true, explanation: "Observed IT completeness and immutability confirmation." },
  { id: "follow-period-postings", primaryDomain: "general_ledger", documentRole: "transactions", filenamePatterns: [/Buchungen_Folgeperiode/i], requiredHeaders: ["BUCHUNGSDATUM", "BELEG", "GEGENKONTO_HB"], primaryKeyCandidates: ["BELEG"], joinKeyCandidates: ["GEGENKONTO_HB", "BELEG"], confidence: 0.94, explanation: "Observed subsequent-period posting extract for cutoff procedures." },
  { id: "ap-january-invoice-journal", primaryDomain: "accounts_payable", documentRole: "transactions", requiredHeaders: ["RECHNUNGSNUMMER", "KREDITOR", "LEISTUNGSDATUM"], filenamePatterns: [/Fakturajournal_Januar_2026_Kreditoren/i], primaryKeyCandidates: ["RECHNUNGSNUMMER"], joinKeyCandidates: ["KREDITOR", "RECHNUNGSNUMMER"], confidence: 0.95, explanation: "Observed January vendor invoice journal with service-period fields." },
  { id: "ar-invoice-journal", primaryDomain: "accounts_receivable", documentRole: "transactions", requiredHeaders: ["RECHNUNGSNUMMER", "DEBITOR", "LEISTUNGSDATUM"], filenamePatterns: [/Fakturajournal_2025/i], primaryKeyCandidates: ["RECHNUNGSNUMMER"], joinKeyCandidates: ["DEBITOR", "RECHNUNGSNUMMER"], confidence: 0.94, explanation: "Observed customer invoice journal fields." },
  { id: "goods-receipts", primaryDomain: "accounts_payable", documentRole: "supporting_document", requiredHeaders: ["WARENEINGANG_NR", "KREDITOR", "RECHNUNGSNUMMER"], filenamePatterns: [/Wareneingangsliste/i], primaryKeyCandidates: ["WARENEINGANG_NR"], joinKeyCandidates: ["KREDITOR", "RECHNUNGSNUMMER"], confidence: 0.94, explanation: "Observed goods-receipt support for vendor invoices." },
  { id: "goods-issues", primaryDomain: "accounts_receivable", documentRole: "supporting_document", requiredHeaders: ["WARENAUSGANG_NR", "DEBITOR", "RECHNUNGSNUMMER"], filenamePatterns: [/Warenausgangsliste/i], primaryKeyCandidates: ["WARENAUSGANG_NR"], joinKeyCandidates: ["DEBITOR", "RECHNUNGSNUMMER"], confidence: 0.94, explanation: "Observed goods-issue support for customer invoices." },
  { id: "customer-credit-limits", primaryDomain: "accounts_receivable", documentRole: "master_data", requiredHeaders: ["DEBITOR", "KREDITLIMIT_EUR"], filenamePatterns: [/Kreditlimitliste/i], primaryKeyCandidates: ["DEBITOR"], joinKeyCandidates: ["DEBITOR"], confidence: 0.94, explanation: "Observed customer credit-limit master data." },
  { id: "ap-open-items", primaryDomain: "accounts_payable", documentRole: "reconciliation", filenamePatterns: [/OP-Liste_Kreditoren/i], sheetPatterns: [/Kreditoren/i], primaryKeyCandidates: ["kreditorennummer"], joinKeyCandidates: ["kreditorennummer", "belegnummer"], confidence: 0.97, trustFilenameOnly: true, explanation: "Observed vendor open-items reconciliation." },
  { id: "ar-open-items", primaryDomain: "accounts_receivable", documentRole: "reconciliation", filenamePatterns: [/OP-Liste_Debitoren/i], sheetPatterns: [/Debitoren/i], primaryKeyCandidates: ["debitorennummer"], joinKeyCandidates: ["debitorennummer", "belegnummer"], confidence: 0.97, trustFilenameOnly: true, explanation: "Observed customer open-items reconciliation." },
  { id: "export-protocol", primaryDomain: "cross_domain_metadata", documentRole: "export_manifest", filenamePatterns: [/Exportprotokoll_GDPdU/i], titlePatterns: [/Exportprotokoll|Datenträgerüberlassung|GDPdU|GoBD/i], confidence: 0.95, explanation: "Observed GDPdU export protocol." },
  { id: "jet-audit-plan", primaryDomain: "audit_planning", documentRole: "audit_plan", titlePatterns: [/Prüfungsplanung|Journal Entry Testing|Wesentlichkeit|Interne Kontrollen/i], filenamePatterns: [/pruefungsplanung|prüfungsplanung|JET/i], confidence: 0.96, explanation: "Observed audit-planning and Journal Entry Testing workpaper markers." },
  { id: "asset-master", primaryDomain: "fixed_assets", documentRole: "master_data", requiredHeaders: ["anlagennummer"], anyHeaders: ["anschaffungswert", "anlagegut", "asset"], primaryKeyCandidates: ["anlagennummer"], joinKeyCandidates: ["anlagennummer"], confidence: 0.95, explanation: "Observed fixed-asset master-data header signature." },
  { id: "asset-transactions", primaryDomain: "fixed_assets", documentRole: "transactions", requiredHeaders: ["anlagennummer"], anyHeaders: ["buchungsdatum", "betrag", "bewegung"], primaryKeyCandidates: ["anlagennummer"], joinKeyCandidates: ["anlagennummer"], confidence: 0.91, explanation: "Observed fixed-asset transaction header signature." },
  { id: "general-ledger", primaryDomain: "general_ledger", documentRole: "transactions", anyHeaders: ["sachkonto", "kontonummer", "buchungstext", "journal"], primaryKeyCandidates: ["belegnummer"], joinKeyCandidates: ["belegnummer", "sachkonto"], confidence: 0.88, explanation: "Observed general-ledger fields." },
  { id: "accounts-payable", primaryDomain: "accounts_payable", documentRole: "transactions", anyHeaders: ["kreditor", "lieferant", "vendor"], primaryKeyCandidates: ["kreditorennummer"], joinKeyCandidates: ["kreditorennummer", "belegnummer"], confidence: 0.84, explanation: "Observed supplier or payable fields." },
  { id: "accounts-receivable", primaryDomain: "accounts_receivable", documentRole: "transactions", anyHeaders: ["debitor", "kunde", "customer"], primaryKeyCandidates: ["debitorennummer"], joinKeyCandidates: ["debitorennummer", "belegnummer"], confidence: 0.84, explanation: "Observed customer or receivable fields." },
  { id: "permissions", primaryDomain: "controls_permissions", documentRole: "control_evidence", anyHeaders: ["berechtigung", "rolle", "user", "approval"], titlePatterns: [/berechtigung|freigabe|permission/i], confidence: 0.86, explanation: "Observed permissions or approval evidence." },
  { id: "financial-report", primaryDomain: "financial_reporting", documentRole: "financial_report", titlePatterns: [/bilanz|guv|jahresabschluss|balance sheet|income statement/i], filenamePatterns: [/bilanz|guv|jahresabschluss/i], confidence: 0.9, explanation: "Observed financial-report title." },
  { id: "schema-manifest", primaryDomain: "cross_domain_metadata", documentRole: "schema_manifest", titlePatterns: [/gdpdu|index|manifest|schema/i], filenamePatterns: [/index\.xml|\.dtd$/i], textPatterns: [/xml|schema|dtd/i], confidence: 0.93, explanation: "Observed XML or schema manifest markers." },
  { id: "audit-plan", primaryDomain: "audit_planning", documentRole: "audit_plan", titlePatterns: [/prüfungsplanung|audit plan/i], filenamePatterns: [/prüfungsplanung|audit.plan/i], confidence: 0.88, explanation: "Observed audit-planning marker." },
  { id: "corporate-structure", primaryDomain: "corporate_structure", documentRole: "supporting_document", anyHeaders: ["gesellschafter", "beteiligung"], filenamePatterns: [/gesellschafter|beteiligung/i], confidence: 0.94, explanation: "Observed corporate-structure marker." },
];
